import { FoundryElement } from '../../core/foundry-element.ts';
import { createStylesheet } from '../../core/stylesheet.ts';
import { createTemplate } from '../../core/template.ts';
import templateHtml from './carousel-slide.template.html?raw';
import styleCss from './carousel-slide.css?inline';

/**
 * A single slide in a `<foundry-carousel>`. Wraps user content in a slot.
 * The parent carousel discovers slides via `slotchange` and projects
 * `selected` onto the matching slide based on its own `value` attribute.
 *
 * @element foundry-carousel-slide
 * @summary A slide inside `<foundry-carousel>`.
 *
 * @attr {string} value - Identifier the parent carousel uses to resolve
 *   the active slide. Auto-generated by the parent when omitted.
 * @attr {boolean} selected - Reflected. Managed by the parent carousel.
 * @attr {string} label - Optional accessible label. When set, the host
 *   exposes `aria-label` so screen readers announce the slide by name.
 *
 * @slot - The slide content.
 *
 * @csspart slide - The host wrapper.
 */
export class FoundryCarouselSlide extends FoundryElement {
  static override properties = {
    value: { type: String, reflect: true },
    selected: { type: Boolean, reflect: true, default: false },
    label: { type: String, reflect: true },
  };

  static override template = createTemplate(templateHtml);
  static override styles = createStylesheet(styleCss);

  static define(tag = 'foundry-carousel-slide'): void {
    if (!customElements.get(tag)) {
      customElements.define(tag, FoundryCarouselSlide);
    }
  }

  override connected(): void {
    // The host is announced as a region with the slide's optional label;
    // the carousel parent owns the broader role="region" and aria-label.
    if (!this.hasAttribute('role')) this.setAttribute('role', 'group');
    this.#syncAriaLabel();
    this.#syncAriaHidden();
  }

  override propertyChanged(name: string): void {
    if (name === 'selected') {
      this.#syncAriaHidden();
    } else if (name === 'label') {
      this.#syncAriaLabel();
    }
  }

  /** Resolved identifier — the `value` attribute, or empty string if unset. */
  get resolvedValue(): string {
    const v = this.readProperty('value');
    return typeof v === 'string' ? v : '';
  }

  #syncAriaLabel(): void {
    const label = this.readProperty('label') as string | undefined;
    if (label) {
      this.setAttribute('aria-label', label);
    } else {
      this.removeAttribute('aria-label');
    }
  }

  #syncAriaHidden(): void {
    // Only the selected slide is exposed to AT; off-screen slides hide
    // from the accessibility tree to avoid duplicate announcements.
    const selected = Boolean(this.readProperty('selected'));
    if (selected) {
      this.removeAttribute('aria-hidden');
    } else {
      this.setAttribute('aria-hidden', 'true');
    }
  }
}
